export const story6 = {
  id: "story6",
  title: "The Easter Bunny in the English Garden",
  file: "https://drive.google.com/file/d/1bqas-3my7VUkqFQaHBwtxNn_t17fs53A/view?usp=sharing",
  pages: [
    {
      id: 1,
      altText: "farm yard",
      text: "Look around. We are on a farm. the grass is green. Are there any buds on the branches? The apricot trees have small white flowers. But the wind is cold. It is spring. It is Easter. The sky is dark. The sun is down. Farmer Jo and his family are sleeping.",
    },
    {
      id: 2,
      altText: "puppy and pig in the farm yard",
      text: "Outside, in the farm yard the cow and the pig are sleeping. The puppy is sleeping too. Then he can hear something. He wakes up. He runs around. Something is in the bushes. He runs to the bushes.",
    },
    {
      id: 3,
      altText: "the puppy and the Easter bunny",
      text: "He can see a bunny. The bunny is not small. The bunny is big and strong. His ears are long. His teeth are sharp. The puppy is nervous, but he says: “Stop! Who are you?” “Don’t be nervous, little puppy!” says the bunny. “I am Easter Bunny! I will not eat carrots and cabbage in your flower beds. I have Easter eggs for your master Jo and his sister.” On his back, he carries a basket full of chocolate eggs. The eggs are in shiny paper. “This is my work day,” he says. “Help me hide the eggs on the farm, please!”“Ok” says the puppy “If you don’t eat carrots and cabbages, I will not bite you.”",
    },
    {
      id: 4,
      altText: "puppy and an egg in a strawberry bed",
      text: "The puppy takes on egg and hides it in the strawberry bed. There are no strawberries now. Then he takes one egg and hides it under the apricot tree. Then he hides one egg under the house wall.",
    },
    {
      id: 5,
      altText: "Easter bunny in pig house",
      text: "The bunny is working too. He hides eggs in the bushes. He hides eggs in the trees. He hides eggs in the pig’s house and in the cow’s house.",
    },
    {
      id: 6,
      altText: "Easter bunny and the puppy look at a roof",
      text: "“Listen, Easter Bunny!” says the puppy “Can you hide an egg on the roof of the house?” “No.” says the bunny. “The roof is high up. Jo and his sister will fall.” “Are the apricot trees tall too?” “No.” says the Easter Bunny. “The apricot trees are not tall. They are short”. They hide the eggs in the house too. “Thank you!” says the Easter Bunny. “I can go now. There are many houses to go” “Good bye” says the puppy. In the house farmer Jo and his sister wake up. Now they can find all the eggs. Inside one house, a family is getting ready for breakfast.",
    },
  ],
  vocabulary: {
    nouns: [
      { word: "garden", meaning: "сад / город" },
      { word: "apricot", meaning: "абрикос" },
      { word: "farmer", meaning: "фермер" },
      { word: "yard", meaning: "двір" },
      { word: "bunny", meaning: "кролик / зайчик" },
      { word: "carrot", meaning: "морква" },
      { word: "cabbage", meaning: "капуста" },
      { word: "flower bed", meaning: "клумба" },
      { word: "master", meaning: "господар" },
      { word: "back", meaning: "спина" },
      { word: "basket", meaning: "кошик" },
      { word: "chocolate", meaning: "шоколад" },
      { word: "work", meaning: "робота" },
      { word: "strawberry", meaning: "полуниця" },
      { word: "wall", meaning: "стіна" },
      { word: "roof", meaning: "дах" },
      { word: "breakfast", meaning: "сніданок" },
    ],
    verbs: [
      { word: "hear", meaning: "чути" },
      { word: "run", meaning: "бігти" },
      { word: "stop", meaning: "зупинятися" },
      { word: "be", meaning: "бути" },
      { word: "eat", meaning: "їсти" },
      { word: "carry", meaning: "нести" },
      { word: "help", meaning: "допомагати" },
      { word: "hide", meaning: "ховати" },
      { word: "take", meaning: "брати" },
      { word: "fall", meaning: "падати" },
      { word: "go", meaning: "йти" },
      { word: "wake up", meaning: "прокидатися" },
      { word: "get ready", meaning: "готуватися" },
    ],
    adjectives: [
      { word: "dark", meaning: "темний" },
      { word: "cold", meaning: "холодний" },
      { word: "strong", meaning: "сильний" },
      { word: "long", meaning: "довгий" },
      { word: "full", meaning: "повний" },
      { word: "shiny", meaning: "блискучий" },
      { word: "high", meaning: "високий (про предмети)" },
      { word: "tall", meaning: "високий (про людей / тварин)" },
      { word: "short", meaning: "короткий / низький" },
      { word: "many", meaning: "багато" },
    ],
    adverbs: [
      { word: "around", meaning: "навколо" },
      { word: "outside", meaning: "надворі / назовні" },
      { word: "too", meaning: "теж" },
      { word: "now", meaning: "зараз" },
      { word: "please", meaning: "будь ласка" },
      { word: "there", meaning: "там" },
    ],
    prepositions: [
      { word: "around", meaning: "навколо" },
      { word: "outside", meaning: "зовні" },
      { word: "on", meaning: "на" },
      { word: "under", meaning: "під" },
      { word: "of", meaning: "з / родовий відмінок" },
      { word: "for", meaning: "для" },
      { word: "inside", meaning: "всередині" },
      { word: "to", meaning: "до / у напрямку до" },
      { word: "up", meaning: "вгору" },
    ],
  },
  tasks: {
    task1: {
      name: "Who can say this",
      list: [
        "“I like the dam.” ",
        "“The dam keeps the river deep, thank you.”",
        "“I can’t cross the river here.”",
        "“This is our home. It keeps us safe.”",
      ],
    },
    task2: {
      name: "Say who can:",
      list: [
        "Who can catch small fish?",
        "Who can swim fast?",
        "Who cannot swim?",
        "Who builds the dam?",
        "Who checks the dam every morning?",
      ],
    },
    task3: {
      name: "Repeat if true (clap if true)",
      list: [
        "Ben has thin grey fur.",
        "Ben lives near a river.",
        "Ben’s father is building a dam.",
        "Molly has brown feathers.",
        "Oliver can swim.",
        "The fox is happy about the dam.",
        "The dam keeps the water deep.",
        "All animals are Ben’s friends.",
      ],
    },
    task4: {
      name: "Say who has:",
      list: [
        "white feathers and yellow beak",
        "long red tail and green eyes",
        "thick brown fur and flat tail",
        "long thick tail",
      ],
    },
  },
  speaking: [
    {
      id: "who-has-red-tail",
      type: "dialogue",
      dialogue: [
        { speaker: "A", line: "Who has red tail?" },
        { speaker: "B", line: "Fox has red tail" },
      ],
      table: {
        column1: ["beaver", "fox", "otter", "duck"],
        column2: "has",
        column3: ["red", "brown", "white", "yellow", "green", "long", "grey"],
        column4: ["teeth", "eyes", "nose", "ears", "tail", "head", "beak"],
      },
      images: [
        "beaver-head",
        "fox-head",
        "otter-head",
        "duck-head",
        "beaver-tail",
        "fox-tail",
        "otter-tail",
        "duck-tail",
      ],
    },
    {
      id: "fox-has-long-tail",
      type: "sentence",
      dialogue: [
        { speaker: "A", line: "Beaver has big" },
        { speaker: "B", line: "teeth" },
      ],
      table: {
        column1: ["beaver", "fox", "otter"],
        column2: "has",
        column3: ["big", "small", "sharp", "wide", "flat", "long"],
        column4: ["teeth", "eyes", "nose", "ears", "tail"],
      },
      images: ["beaver", "fox", "otter"],
    },
  ],
  games: {nouns: "https://learningapps.org/watch?v=pjjs1d7g226"}
};
